apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-meaword
spec:
  displayName: MeaWord
  author:
    name: loster
    website: https://dzbook.com
  description: 简洁书
  logo: /themes/theme-meaword/assets/images/logo_icon.png
  website: https://dzbook.com
  repo: https://github.com/losterich/brevity-book.git
  settingName: theme-meaword-setting
  configMapName: theme-meaword-configmap
  version: 1.0
  requires: ">=2.1.0"